# Generated by Django 2.0.6 on 2018-07-08 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_c',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_d',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='equation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='grade_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='problem_statement',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='question',
            name='tips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
