# Generated by Django 2.0.6 on 2018-07-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180709_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=1000)),
                ('grade_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1', max_length=1)),
                ('test_type', models.CharField(choices=[('F', 'Finals'), ('E', 'Elims'), ('P', 'Practice'), ('T', 'Team')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_question', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test')),
            ],
        ),
        migrations.AlterField(
            model_name='question_subject',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question_subject',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
