# Generated by Django 2.0.6 on 2018-07-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
