# Generated by Django 2.0.6 on 2018-07-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180717_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('F', 'Finals'), ('E', 'Elims'), ('P', 'Practice'), ('T', 'Team')], default='P', max_length=1)),
                ('points', models.IntegerField(default=1)),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time', models.IntegerField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Student')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Test')),
            ],
        ),
    ]
