# Generated by Django 2.0.6 on 2018-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_test_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_submission',
            name='elapsed_time',
            field=models.DurationField(),
        ),
    ]
