# Generated by Django 2.0.6 on 2018-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20180717_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_submission',
            name='elapsed_time',
            field=models.IntegerField(default=1),
        ),
    ]
