# Generated by Django 2.0.6 on 2018-07-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20180717_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('F', 'Finals'), ('E', 'Elims'), ('P', 'Practice'), ('T', 'Team')], default='P', max_length=1)),
                ('submitted_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time', models.IntegerField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Test_Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Test')),
                ('test_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test_Submission')),
            ],
        ),
    ]
