# Generated by Django 2.0.6 on 2018-07-16 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='awards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
